---
title: "L17Ex_PneumoconiosisData"
author: "Rick Davila"
date: "6/14/2020"
output:
  md_document:
    variant: markdown_github
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)

#Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jdk-14.0.1') # for 64-bit version
#library(rJava)
library(MASS)

# Example 13.1 (p. 426-427) ###
# Create data frame with problem data

years <- c(5.8,15.0,21.5,27.5,33.5,39.5,46.0,51.5)
cases <- c(0,1,3,8,9,8,10,5)
miners <- c(98,54,43,48,51,38,28,11)
ymat <- cbind(cases,miners-cases)

p_data <- data.frame(ymat, years)

# Perform logistic regression using glm(). Compare output to Table 13.2 on p. 427.

model.131 <- glm(ymat ~ years, binomial(link = "logit"))
model.131

```


```{r}

# Example 13.2 (p. 428)
# Calculate odds ratio for the regressor variable; compare to p. 428 

odds_ratio <- exp(model.131$coefficients[2])
odds_ratio

```


odds ratio = $`r odds_ratio`$


```{r}

# Example 13.3 (p. 434-436)
# Add a quadratic term to the model

years_sq <- years*years
model.133 <- glm(ymat ~ years + years_sq, binomial(link = "logit"))
model.133

```


```{r}

# Example 13.4 (p. 437) ###
# Test each regression coefficient for significance automatically using the summary() command

summary(model.133)

```


```{r}

# Example 13.5 (p. 438) ###
# Calculate confidence intervals automatically using confint()
confint.default(model.133)


# Calculate by hand using Equation (13.25)
Z_crit <- qnorm(1-.05/2)
se_beta_0 <- coef(summary(model.133))[, "Std. Error"][1]
se_beta_1 <- coef(summary(model.133))[, "Std. Error"][2]
se_beta_11 <- coef(summary(model.133))[, "Std. Error"][3]

OR_Upper_0 <- model.133$coefficients[1] + Z_crit*se_beta_0
OR_Lower_0 <- model.133$coefficients[1] - Z_crit*se_beta_0
OR_Upper_1 <- model.133$coefficients[2] + Z_crit*se_beta_1
OR_Lower_1 <- model.133$coefficients[2] - Z_crit*se_beta_1
OR_Upper_11 <- model.133$coefficients[3] + Z_crit*se_beta_11
OR_Lower_11 <- model.133$coefficients[3] - Z_crit*se_beta_11

```

approximate 95% confidence intervals calculated by hand

$$\hat{\beta}_0-Z_{0.025}\text{se}(\hat{\beta}_0)\le\beta_0\le\hat{\beta}_0+Z_{0.025}\text{se}(\hat{\beta}_0)$$
$$`r OR_Lower_0` \le \beta_0\le `r OR_Upper_0`$$
$$\hat{\beta}_1-Z_{0.025}\text{se}(\hat{\beta}_1)\le\beta_1\le\hat{\beta}_0+Z_{0.025}\text{se}(\hat{\beta}_1)$$
$$`r OR_Lower_1` \le \beta_1\le `r OR_Upper_1`$$

$$\hat{\beta}_{11}-Z_{0.025}\text{se}(\hat{\beta}_{11})\le\beta_{11}\le\hat{\beta}_{11}+Z_{0.025}\text{se}(\hat{\beta}_{11})$$
$$`r OR_Lower_11` \le \beta_{11}\le `r OR_Upper_11`$$


```{r}

# Example 13.6 (p. 438) ###
# On the original model, calculate a 95% confidence interval on the odds ratio using Equation (13.26)

odds_ratio <- exp(coef(model.133))
# 95% CI on odds ratio
Z_crit <- qnorm(1-.05/2)
OR_Upper <- exp(coef(model.133) + Z_crit*sqrt(diag(vcov(model.133))))
OR_Lower <- exp(coef(model.133) - Z_crit*sqrt(diag(vcov(model.133))))

```

$$exp[\hat{\beta}_{j}-Z_{\alpha/2}\text{se}(\hat{\beta}_{j})]\le O_{R}\le exp[\hat{\beta}_{j}+Z_{\alpha/2}\text{se}(\hat{\beta}_{j})]$$

$$`r OR_Lower[1]` \le O_R=\hat{\beta_0}\le `r OR_Upper[1]`$$
$$`r OR_Lower[2]` \le O_R=\hat{\beta_1}\le `r OR_Upper[2]`$$
$$`r OR_Lower[3]` \le O_R=\hat{\beta_{11}}\le `r OR_Upper[3]`$$

##### Example 13.7 (p. 439-440) ###
##### Create a 95% confidence interval on the predicted probability of Years = 40.

```{r}

# Calculate predicted probability using predict(); compare to p. 439
# note, type = "response" gives the predicted probabilities
predict(model.131,type="response",se.fit=TRUE,newdata=data.frame(years=40))

```

```{r}

# calculate the predicted linear predictor using predict(); compare to p. 439
# note, type - default is on the scale of the linear predictors
predict(model.131,se.fit=TRUE,newdata=data.frame(years=40))

```

```{r}

# Define vector for the new observation

x_0 <- c(1,40)

# Calculate the variance of the new observation. The function vcov() automatically calculates the inverse of X'VX. 

XtVX <- vcov(model.131)

# Calculate CI on linear predictor using Equation (13.27)

Z_crit <- qnorm(1-.05/2)
Ux_0 <- t(x_0) %*% coef(model.131) + Z_crit*sqrt(t(x_0) %*% XtVX %*% x_0)
Lx_0 <- t(x_0) %*% coef(model.131) - Z_crit*sqrt(t(x_0) %*% XtVX %*% x_0)

# Convert to probabilities using Equation (13.28)
LowerP <- exp(Lx_0)/(1+exp(Lx_0))
UpperP <- exp(Ux_0)/(1+exp(Ux_0))

```


Calculate CI on linear predictor using Equation (13.27)

$$x'_0\hat{\beta}-Z_{\alpha/2}\sqrt{x'_0(X'VX)^{-1}x_0}\le x'_0\hat{\beta}\le x'_0\hat{\beta}+Z_{\alpha/2}\sqrt{x'_0(X'VX)^{-1}x_0}$$

$$`r Lx_0`\le x'_0\hat{\beta}\le `r Ux_0`$$


Convert to probabilities using Equation (13.28)

$$\frac{exp[L(x_0)]}{1+exp[L(x_0)]}\le\pi_0\le\frac{exp[U(x_0)]}{1+exp[U(x_0)]}$$

$$`r LowerP`\le\pi_0\le`r UpperP`$$



